### ISSUE TITLE
Request Failed -- 503 -- Service Unavailable -- Is Reactome API down? 

### ISSUE THREAD

**Issue by hcchau418** [reactome/ReactomeGSA#38] opened 2021-09-09 00:30 UTC
Error in start_reactome_analysis (request = request, compress = compress, : Request failed (503 - Service Unavailable): The number of analysis requests is currently too high. Please try again in a few minutes.

Hello! I keep running into this error when I run my analysis, which worked this morning: 

gssva_result <- analyse_sc_clusters(experiment.sample2,use_interactors = TRUE,
  include_disease_pathways = TRUE,
  create_reactome_visualization = FALSE,
  create_reports = FALSE,
  report_email = NULL,
  verbose = TRUE)

**Comment by Ankita-1211** [comment] 2021-09-09 03:47
Hi 
Even I am getting the same error since yesterday.
Request failed (503 - Service Unavailable): The number of analysis requests is currently too high. Please try again in a few minutes.

**Comment by jgriss** [comment] 2021-09-09 06:26
Hi @hcchau418 and @Ankita-1211 ,

Thanks a lot for reporting this issue! This was caused by an issue with our cluster. It should be fixed now.

The service is up and available again.

Kind regards,
Johannes

**Closed by jgriss** 2021-09-09 06:26 UTC
Labels: bug
