### ISSUE TITLE
scRNA-seq pathway scoring per condition 

### ISSUE THREAD

**Issue by FADHLyemen** [reactome/ReactomeGSA#24] opened 2021-06-18 15:16 UTC
I would like to compute pathway activity score among clusters and compare two group of patients. something such below: 
But it should be clusters and samples in the column instead of samples alone.
![image](https://user-images.githubusercontent.com/23288387/122582791-8d20be00-d026-11eb-8052-6d9b3ab0573b.png)

**Comment by jgriss** [comment] 2021-06-18 18:45
Hi,

Thanks a lot for your interest in ReactomeGSA!

The function uses the primary cell identifier to calculate the average expression per entity.

For Seurat, this is accessible through Idents (your_object).

Simply change this to your cluster + sample identifier before you run the pathway analysis.

Kind regards,
Johannes

On 18 June 2021 17:16:55 CEST, Fadhl ***@***.***> wrote:
>I would like to compute pathway activity score among clusters and
>compare two group of patients. something such below: 
>But it should be clusters and samples in the column instead of samples
>alone.
>![image](https://user-images.githubusercontent.com/23288387/122582791-8d20be00-d026-11eb-8052-6d9b3ab0573b.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/24

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FADHLyemen** [comment] 2021-06-18 21:23
Thank you, I still need to compare the clusters

**Comment by jgriss** [comment] 2021-06-18 21:27
Simply combine the cluster id with the sample is using, for example, paste0. Then you get one value per sample and cluster.

Kind regards,
Johannes

On 18 June 2021 23:23:14 CEST, Fadhl ***@***.***> wrote:
>Thank you, I still need to compare the clusters
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/24#issuecomment-864282013

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FADHLyemen** [comment] 2021-06-25 19:21
Thank you, I am wondering after you get the `av_counts`  what shall you do with it?
what is the mathematics/code to compute the activity score from it?

**Comment by jgriss** [comment] 2021-06-26 19:26
Hi @FADHLyemen 

I'm not quite sure I fully understand your question. As soon as you adapt your `Ident`accordingly you can revert to use the default ReactomeGSA functions.

Kind regards,
Johannes

**Comment by FADHLyemen** [comment] 2021-07-09 02:54
I have some genes and I need to compute the pathway score.
it is the average expression of these genes grouped by cell types. CODE something like

```
av_counts %>% data.frame()%>%rownames_to_column('sample') %>% filter(sample %in% c('KCNK3','KCNK9')) %>%
column_to_rownames("sample") %>% 
#scale %>% 
colMeans %>%
data.frame(SGLTI=.)
```

**Comment by jgriss** [comment] 2021-07-09 19:11
This seems to be a duplicate of the follow up question to #25 

Please only ask a question once.

**Closed by jgriss** 2021-07-09 19:11 UTC
